Домашнее задание №2
htmlacademy-htmlcss/1722589-technomart-31 pull request #2
Opened 2021-05-22 13:28 UTC by Ray-Garraty

Создал базовую HTML-структуру _index.html_ и _catalog.html_.

2021-05-23 16:28 UTC, PavelNyukalo requested changes

2021-05-23 16:28 UTC, PavelNyukalo commented on index.html
> +            <p>NEW</p>
Тут тоже про текст в верхнем регистре (относится ко всему такому тексту)
И второе - иконки тоже сделаем потом через фон

2021-05-23 16:28 UTC, PavelNyukalo commented on index.html
> +          </li>
По [ТЗ](https://up.htmlacademy.ru/htmlcss/31/project/technomart#technomart-3-9) вся карточка должна быть ссылкой

2021-05-23 16:28 UTC, PavelNyukalo commented on index.html
> +          <h3>Популярные товары:</h3>
Не очень хорошо, что заголовки повторяются - скринридер прочитает их дважды.
Тут можно оставить один - тот, что в `div` лежит

2021-05-23 16:28 UTC, PavelNyukalo commented on index.html
> +          <a href="#">ВСЕ ПРОИЗВОДИТЕЛИ</a>
Аналогично с заголовками

2021-05-23 16:28 UTC, PavelNyukalo commented on index.html
> +          <button type="button">ОТПРАВИТь ЗАЯВКУ</button>
Здесь как раз-таки подойдет ссылка

2021-05-23 16:28 UTC, PavelNyukalo commented on index.html
> +        <button type="button">ЗАБЛУДИЛИСЬ? НАПИШИТЕ НАМ!</button>
По [ТЗ](https://up.htmlacademy.ru/htmlcss/31/project/technomart#technomart-4-4) это у нас элемент, вызывающий появление попапа, а по критериям ([Д20](https://up.htmlacademy.ru/htmlcss/31/criteries#d20)) - он должен быть ссылкой

2021-05-23 16:28 UTC, PavelNyukalo commented on index.html
> +          <p>+7 800 555-86-28</p>
Тоже ссылочка ([Д29](https://up.htmlacademy.ru/htmlcss/31/criteries#d29))

2021-05-23 16:28 UTC, PavelNyukalo commented on index.html
> +        <input type="submit" value="ОТПРАВИТЬ">
Для кнопки отправки обычно используют `button`

2021-05-24 17:03 UTC, Ray-Garraty commented on index.html
> +          </li>
Не могу найти такого требования в ТЗ. А что должно происходить по клику на карточке с товаром? Нас должно перекидывать на страницу с описанием товара или что-то другое?

2021-05-24 18:50 UTC, PavelNyukalo commented on index.html
> +          </li>
Пункт 3.9. Предполагаем, что да - перекидывает на другую страницу, или при помощи JS открывается попап, например. Все это уточняется у дизайнеров, но у нас такой возможности нет, поэтому следуем ТЗ

2021-05-24 18:59 UTC, PavelNyukalo requested changes

2021-05-24 18:59 UTC, PavelNyukalo commented on index.html
>            <h3>Популярные товары:</h3>
Убрав `h2` у нас нарушилась структура заголовков - у всех секций начинается с `h2`, а тут сразу с `h3` . Поэтому этот `h3` поменяй на `h2`, а ниже `h4` на `h3`

2021-05-24 18:59 UTC, PavelNyukalo commented on index.html
>            <h3>Популярные производители:</h3>
Здесь так же, как выше

2021-05-25 17:38 UTC, Ray-Garraty commented on index.html
> +          </li>
Из описания ТЗ я подумал, что пункт 3.9 относится не к этому блоку ("Популярные товары"), а к другому ("Популярные производители"). Ну в любом случае, я исправил.

2021-05-25 18:55 UTC, PavelNyukalo approved these changes

2021-05-25 18:55 UTC, merged