Разметка вспомогательной страницы
htmlacademy-htmlcss/1722589-technomart-31 pull request #3
Opened 2021-05-25 19:45 UTC by Ray-Garraty

Создал разметку страницы catalog.html

2021-05-25 19:55 UTC, Ray-Garraty commented
Пришлось убрать кнопки изнутри 3-й карточки товара (в 1-м ряду), т.к. по ТЗ карточка - это ссылка, а внутри ссылки нельзя размещать кнопки или другие ссылки (валидатор ругается).

2021-05-26 17:52 UTC, PavelNyukalo requested changes
В тех местах, где GitHub не дает мне возможности прокомментировать, я напишу здесь.
1. Строка 34-35. По [ТЗ 3.4](https://up.htmlacademy.ru/htmlcss/31/project/technomart#technomart-3-4) имя и "выйти" должны быть ссылками
2. Строка 48. Убери ссылку на каталог
3. Строки 65, 68, 71. Так же можно убрать верхний регистр
4. Строка 275. Картинку галочки можно через псевдоэлемент и фон потом добавить, в разметке она лишняя

2021-05-26 17:52 UTC, PavelNyukalo commented on catalog.html
>        <p>Сортировка:</p>
При построении сетки потом возможно надо будет немного переделать верстку для 
```html
<p>Перфораторы</p>
<p>Фильтр:</p>
<p>Сортировка:</p>
```
на примерно такую (т.е. раскидать по секциям)
![image](https://user-images.githubusercontent.com/52506235/119706158-0d626200-be73-11eb-9ad7-be2d478fcebf.png)

2021-05-26 17:52 UTC, PavelNyukalo commented on catalog.html
> +            <a href="#">
Комментарий насчет ссылки видел - это требование только для `index`,
![image](https://user-images.githubusercontent.com/52506235/119707474-9cbc4500-be74-11eb-9def-beb9a4308216.png)
 так что тут можно не оборачивать в ссылку, и использовать спокойно кнопки (кстати кнопки должны быть не только у 3 карточки, а появляться при наведении на любую, это по стайлгайду)
![image](https://user-images.githubusercontent.com/52506235/119707349-7dbdb300-be74-11eb-8235-5a3a2883551d.png)

2021-05-27 16:08 UTC, PavelNyukalo approved these changes

2021-05-27 16:08 UTC, merged